apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: aikit-operator
  namespace: openshift-operators
spec:
  channel: alpha
  name: aikit-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
