apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ovms-operator
  namespace: openshift-operators
spec:
  channel: alpha
  name: ovms-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: openvino-operator.v1.0.0
