apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhods-cleanup
  namespace: redhat-ods-applications
---
# Allow the cleanup job to check if an OCP user exists
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhods-query-users
rules:
  - apiGroups:
      - ""
      - user.openshift.io
    resources:
      - groups
      - identities
      - useridentitymappings
      - users
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhods-query-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhods-query-users
subjects:
  - kind: ServiceAccount
    name: rhods-cleanup
    namespace: redhat-ods-applications
---
# Allow the cleanup job delete resources in the rhods-notebooks namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rhods-notebooks-cleanup
  namespace: rhods-notebooks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: rhods-cleanup
    namespace: redhat-ods-applications
---
# Allow the cleanup job delete resources in the redhat-ods-applications namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rhods-applications-cleanup
  namespace: redhat-ods-applications
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: rhods-cleanup
    namespace: redhat-ods-applications
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rhods-cleanup
  namespace: redhat-ods-applications
spec:
  schedule: '0 * * * *'
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 200
  suspend: false
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: rhods-cleanup
              # Custom image to provide oc cli and jq
              image: quay.io/modh/rhods-cleanup:latest
              env:
                - name: JUPYTERHUB_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: jupyterhub-idle-culler
                      key: token
                - name: JUPYTERHUB_NOTEBOOK_NAMESPACE
                  value: rhods-notebooks
                - name: JUPYTERHUB_API_URL
                  value: http://jupyterhub:8081/hub/api
                - name: JUPYTERHUB_APPLICATION_NAMESPACE
                  value: redhat-ods-applications
              command: ["cleanup.sh"]
          serviceAccount: rhods-cleanup
          serviceAccountName: rhods-cleanup
          restartPolicy: Never
